# Generated by Django 3.2 on 2021-04-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whats_new', '0002_research_update_link_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('page_link', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='research_update',
            name='link',
        ),
        migrations.AddField(
            model_name='research_update',
            name='link_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='research_update',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whats_new.latest_research_year'),
        ),
        migrations.CreateModel(
            name='Site_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message_p1', models.CharField(max_length=254)),
                ('link_1_url', models.URLField(blank=True)),
                ('link_1_name', models.CharField(blank=True, max_length=56)),
                ('message_p2', models.CharField(blank=True, max_length=254)),
                ('link_2_url', models.URLField(blank=True)),
                ('link_2_name', models.CharField(blank=True, max_length=56)),
                ('updated_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whats_new.site_page')),
            ],
        ),
    ]
