# Generated by Django 3.2 on 2021-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_of_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=120)),
                ('comments', models.CharField(blank=True, max_length=500)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
