# Generated by Django 3.2 on 2021-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('image_link', models.URLField()),
                ('description', models.CharField(max_length=1254)),
                ('optional_link', models.URLField(blank=True)),
                ('optional_link_text', models.CharField(blank=True, max_length=124)),
            ],
        ),
    ]
